<?


class lang{
        var $lang=NULL;
        var $db_words=array();

        function __construct($language)
        {
                $this->lang=$language;
		if($this->check_lang())
		{
			$this->parse_lang_file();
		}
        }


        function get($string){
		if($this->lang != "en" && $this->lang != NULL ){
	                return (isset($this->db_words[strtolower($string)])) ? $this->db_words[strtolower($string)] : $string;
		}else{
	                return $string;
		}
        }

	function parse_lang_file()
	{
		$data_file=file_get_contents($this->lang."/".$this->lang.".txt");
		$data_file_strings=explode("\n",$data_file);
		foreach($data_file_strings as $key => $val)
		{
			if($val != NULL && $val != '')
			{			
				$data_string=explode("=",$val);
				if($data_string[1] != '' && $data_string[0] != '')
				{
					$this->db_words[strtolower($data_string[0])]=$data_string[1];
				}
			}
		}
	}

	function check_lang()
	{
		$res=FALSE;
		if (file_exists($this->lang) && is_dir($this->lang)) 
		{
			if(is_readable($this->lang."/".$this->lang.".txt"))
			{
				$res=TRUE;
			}	
		}
		return $res;
	}

	
        function db_lang(){
                $this->db_words=array(
                "work"=>array("ru"=>"Работать"),
                "pause"=>array("ru"=>"Пауза"),
		"you have now logged out. thank you"=>array("ru"=>"Вы вышли из системы. Спасибо"),
                "Refresh Campaing List"=>array("ru"=>"Обновить список кампаний"),
                "Title"=>array("ru"=>"Должность"),
                "First"=>array("ru"=>"Имя"),
                "MI"=>array("ru"=>""),
                "Last"=>array("ru"=>"Фамилия"),
                "Address1"=>array("ru"=>"Адрес 1"),
                "Address2"=>array("ru"=>"Адрес 2"),
                "Address3"=>array("ru"=>"Адрес 3"),
                "City"=>array("ru"=>"Город"),
                "State"=>array("ru"=>"Штат"),
                "Province"=>array("ru"=>"Область"),
                "PostCode"=>array("ru"=>"Почт. индекс"),
                "Vendor ID"=>array("ru"=>"Код п."),
                "Gender"=>array("ru"=>"Пол"),
                "Phone"=>array("ru"=>"Телефон"),
                "DialCode"=>array("ru"=>"Префикс"),
                "Alt. Phone"=>array("ru"=>"Доп. телефон"),
                "Show"=>array("ru"=>"Показать"),
                "Email"=>array("ru"=>"Почта"),
                "Comments"=>array("ru"=>"Заметки"),
                "version"=>array("ru"=>"Версия"),
                "browser"=>array("ru"=>"Браузер"),
                "build"=>array("ru"=>"Сборка"),
                "User Login Error"=>array("ru"=>"Ошибка авторизации"),
		"Phone Login Error"=>array("ru"=>"Ошибка данных телефона"),
                "Agent web client"=>array("ru"=>"Веб клиент"),
                "Re-Login"=>array("ru"=>"Повторный вход"),
                "Phone Login"=>array("ru"=>"Номер телефона"),
                "Phone Password"=>array("ru"=>"Пароль телефона"),
                "User Login"=>array("ru"=>"Логин"),
                "User Password"=>array("ru"=>"Пароль"),
                "Campaign"=>array("ru"=>"Кампания"),
                "submit"=>array("ru"=>"Ввод"),
                "Campaign Login"=>array("ru"=>"Вход в кампанию"),
                "Login"=>array("ru"=>"Логин"),
                "YOU MUST LOG IN TO THE TIMECLOCK FIRST"=>array("ru"=>"СНАЧАЛА НУЖНО ОТМЕТИТЬСЯ В ТАБЕЛЬНЫХ ЧАСАХ"),
                "There are no Shifts enabled for your user group"=>array("ru"=>"для Вашей группы нет разрешенных смен"),
                "error"=>array("ru"=>"Ошибка"),
                "You are not allowed to log in outside of your shift"=>array("ru"=>"Вам не разрешено входить в систему вне своей смены"),
                "MANAGER OVERRIDE"=>array("ru"=>"УКАЗАТЬ ДРУГОГО НАЧАЛЬНИКА"),
                "Manager Login"=>array("ru"=>"Начальник Имя"),
                "Manager Password"=>array("ru"=>"Начальник Пароль"),
                "leads left to call in hopper"=>array("ru"=>"номера для обзвона в буфере"),
                "Campaign not active, please try again"=>array("ru"=>"Кампания не активна, пожалуйста попробуйте снова."),
                "Login incorrect, please try again"=>array("ru"=>"Имя неверно, попробуйте еще раз, пожалуйста"),
		"Too many login attempts, try again in 15 minutes"=>array("ru"=>"Слишком много попыток, попробуйте снова через 15 минут"),
                "mute"=>array("ru"=>"Выкл. микрофон"),
                "unmute"=>array("ru"=>"Вкл. микрофон"),
                "Alert is OFF"=>array("ru"=>"оповещение выключено"),
                "Alert is ON"=>array("ru"=>"оповещение включено"),
                "Sorry, your phone login and password are not active in this system, please try again"=>array("ru"=>"Извините, Ваш телефон и его пароль не активировны в системе, попробуйте еще раз, пожалуйста"),
                "Sorry, you are not allowed to login to this campaign"=>array("ru"=>"Извенить, у вас нет доступа в эту кампанию"),
		"System Delay, Please try again"=>array("ru"=>"Система задержки, пожалуйста, попробуйте еще раз"),
		"Dial next"=>array("ru"=>"Набрать следующий номер"),
		"Preview the Lead then"=>array("ru"=>"Предпросмотр сведений о номере"),
		"Waiting for Ring..."=>array("ru"=>"Ожидание звонка..."),
		"No more leads in the hopper for campaign"=>array("ru"=>"В буфере больше нет номеров для кампании"),
		"This phone number is in the DNC list"=>array("ru"=>"Этот номер телефона в DNC списке"),
		"This phone number is not in the campaign lists"=>array("ru"=>"Этого телефонного номера нет в списках кампании"),
		"This phone number is outside of the local call time"=>array("ru"=>"Этот телефон находится вне местного времени вызова"),
		"Unspecified error"=>array("ru"=>"Неизвестная ошибка"),
		"Web form"=>array("ru"=>"Веб форма"),
		"Web form 2"=>array("ru"=>"Веб форма 2"),
		"PREVIOUS CALLBACK"=>array("ru"=>"Предпросмотр обратного вызова"),
		"Last Cal"=>array("ru"=>"Последний вызов"),
		"CallBack"=>array("ru"=>"Обратный вызов"),
		"Agent"=>array("ru"=>"Агент"),
		"Lead was not reverted, there was an error"=>array("ru"=>"Номер не был возвращен из-за ошибки"),
		"Lead skipped, go on to next lead"=>array("ru"=>"Lead skipped, go on to next lead"),
		"ALT DIAL NUMBER"=>array("ru"=>"ДОПОЛНИТЕЛЬНЫЙ НОМЕР"),
		"ALT"=>array("ru"=>"заместитель"),
		"Phone Code and Number"=>array("ru"=>"Код набора и номер:"),
		"Active"=>array("ru"=>"Активный"),
		"Notes"=>array("ru"=>"Примечания"),
		"Alt Count"=>array("ru"=>"Доп. счетчик:"),
		"call was not placed, there was an error"=>array("ru"=>"вызов не был произведен из-за ошибки"),
		"Calling"=>array("ru"=>"Вызываю"),
		"Incoming"=>array("ru"=>"Входящие"),
		"CALL DISPOSITION"=>array("ru"=>"КОД ЗАВЕРШЕНИЯ ВЫЗОВА"),
		"Disposition Status List Hidden"=>array("ru"=>"Скрытый список кодов завершения звонка"),
		"YOU MUST BE PAUSED TO ENTER A PAUSE CODE IN AUTO-DIAL MODE"=>array("ru"=>"В РЕЖИМЕ АВТОДОЗВОНА ДЛЯ ВВОДА КОДА ПАУЗЫ НУЖНО БЫТЬ В СОСТОЯНИИ ПАУЗЫ"),
		"PAUSE CODE"=>array("ru"=>"Код паузы"),
		"Go Back"=>array("ru"=>"Вернуться"),
		"YOU MUST BE PAUSED TO SEARCH FOR A LEAD"=>array("ru"=>"Для поиска клиента, вы должны быть в состоянии ПАУЗА"),
		"YOU MUST BE ON AN ACTIVE INBOUND CALL TO SEARCH FOR A LEAD"=>array("ru"=>"Для поиска клиента, вы должны быть в состоянии ПАУЗА"),
		"Close [X]"=>array("ru"=>"Закрыть [X]"),
		"DIAL IN-GROUP"=>array("ru"=>"Вызов в группу"),
		"You Must Select a Disposition"=>array("ru"=>"Вы должны выбрать код завершения"),
		"Hangup Again"=>array("ru"=>"Снова завершить вызов"),
		"Next Call Pause"=>array("ru"=>"Следующая пауза вызова"),
		"Group Alias"=>array("ru"=>"Псевдоним группы"),
		"GROUPS NOT SELECTED"=>array("ru"=>"Не выбранные групп"),
		"SELECTED GROUPS"=>array("ru"=>"Выбранные группы"),
		"---ADD-ALL---"=>array("ru"=>"Добавить всё"),
		"Manager has selected groups for you"=>array("ru"=>"Начальник назначил Вам входящие группы"),
		"---DELETE-ALL---"=>array("ru"=>"Удалить всё"),
		"TERRITORIES NOT SELECTED"=>array("ru"=>"Не выбранные территории"),
		"SELECTED TERRITORIE"=>array("ru"=>"Выбранные территории"),
		"PLEASE CLICK THE LOGOUT LINK TO LOG OUT NEXT TIME"=>array("ru"=>"PLEASE CLICK THE LOGOUT LINK TO LOG OUT NEXT TIME"),
		"STILL A LIVE CALL! Hang it up then you can log out"=>array("ru"=>"ВЫЗОВ ВСЕ ЕЩЕ АКТИВЕН! Завершите его, а потом выходите из системы"),
		"You are in ALT dial mode, you must finish the lead before logging out"=>array("ru"=>"Вы находитесь в режиме набора ALT, вы должны закончить свинца до выхода из"),
		"You cannot log out during a Dial attempt. \nWait 50 seconds for the dial to fail out if it is not answered"=>array("ru"=>'Нельзя выйти из системы во время дозвона. \nЕсли на звонок не отвечают, подождите 50 секунд до истечения времени дозвона'),
		"Your Shift is over or has changed, you have been logged out of your session"=>array("ru"=>"Ваша смена закончилась или изменена, Вы были выведены из своей сессии"),
		"The system has received a command to log you out, you have been logged out of your session"=>array("ru"=>"Система получила команду войти вы, вы вышли из вашей сесси"),
		"YOU MUST BE PAUSED TO GRAB CALLS IN QUEUE"=>array("ru"=>"ЧТОБЫ ВЗЯТЬ ВЫЗОВ ИЗ ОЧЕРЕДИ НУЖНО БЫТЬ В СОСТОЯНИИ ПАУЗЫ"),
		"Hide Calls In Queue"=>array("ru"=>"Спрятать вызовы в очереди"),
		"Show Calls In Queu"=>array("ru"=>"Показать вызовы в очереди"),
		"YOU MUST BE PAUSED TO VIEW YOUR CALL LOG"=>array("ru"=>"Для просотра истории, вы должны быть в состоянии ПАУЗА"),
		"Next Call Pause Set"=>array("ru"=>"Следующая пауза вызова Set"),
		"YOU MUST BE PAUSED TO CHANGE GROUPS"=>array("ru"=>"ДЛЯ СМЕНЫ ГРУПП НУЖНО БЫТЬ В СОСТОЯНИИ ПАУЗЫ"),
		"Manager"=>array("ru"=>"Начальник"),
		"YOU MUST BE PAUSED TO CHANGE TERRITORIES"=>array("ru"=>"YOU MUST BE PAUSED TO CHANGE TERRITORIES"),
		"You must choose a date"=>array("ru"=>"Вы должны выбрать дату"),
		"DIAL ALERT"=>array("ru"=>"набрать Уведомления"),
		"TIMER NOTIFICATION"=>array("ru"=>"УВЕДОМЛЕНИЕ ПО ТАЙМЕРУ"),
		"seconds"=>array("ru"=>"секунд"),
		"ENTER A PAUSE CODE"=>array("ru"=>"ВВЕСТИ КОД ПАУЗЫ"),
		"Manual Queue is Off"=>array("ru"=>"Руководство Очередь Off"),
		"Time On Park"=>array("ru"=>"В ожидании"),
		"Customer Hung-up, 3-way Call Ended Automatically"=>array("ru"=>"Клиент Хун-до, 3-полосная окончании разговора автоматически"),
		"CUSTOMER 3WAY HANGUP"=>array("ru"=>"CUSTOMER 3WAY зависание"),
		"LEAD PREVIEW"=>array("ru"=>"Предпросмотр сведений о номере"),
		"ALT PHONE DIAL"=>array("ru"=>"НАБОР ДОП.НОМЕРА"),
		"Hide conference call channel information"=>array("ru"=>"Скрыть сведения о линии конференции"),
		"Show conference call channel information"=>array("ru"=>"Показать сведения о линии конференции"),
		"YOU DO NOT HAVE PERMISSIONS TO TRANSFER CALLS"=>array("ru"=>"ВАМ НЕ РАЗРЕШЕНО ПЕРЕВОДИТЬ ВЫЗОВЫ"),
		"CLICK HERE TO LOG IN AGAIN"=>array("ru"=>"КЛИКНИТЕ ЗДЕСЬ ДЛЯ ПОВТОРНОГО ВХОДА В СИСТЕМУ"),
		"Local time"=>array("ru"=>"Текущие время"),
		"session ID"=>array("ru"=>"Номер сессии"),
		"volumeup"=>array("ru"=>"Увеличить громкость клиента"),
		"volumedown"=>array("ru"=>"Уменьшить громкость клиента"),
		"VIEW CALL LOG"=>array("ru"=>"Журнал вызовов"),
		"MANUAL DIAL"=>array("ru"=>"Ручной набор"),
		"FAST DIAL"=>array("ru"=>"Быстрый набор"),
		"Status"=>array("ru"=>"Состояние"),
		"sec"=>array("ru"=>"сек"),
		"Group"=>array("ru"=>"Группа"),
		"Fronter"=>array("ru"=>"Агент"),
		"UID"=>array("ru"=>"Уник. номер"),
		"Lead"=>array("ru"=>"Клиент"),
		"List"=>array("ru"=>"Список"),
		"TERRITORIES"=>array("ru"=>"Территории"),
                "Work"=>array("ru"=>"Работать"),
                "Pause"=>array("ru"=>"Пауза"),
                "Start Recording"=>array("ru"=>"Начать запись"),
                "Stop Recording"=>array("ru"=>"Остановить запись"),
                "Send DTMF"=>array("ru"=>"Отправить DTMF"),
                "GRAB PARKED CALL"=>array("ru"=>"Снять с музыки"),
                "Park Call"=>array("ru"=>"Поставить на музыку"),
                "Record File"=>array("ru"=>"Файл записи"),
                "Record ID"=>array("ru"=>"Номер Записи"),
                "Transfer Conf"=>array("ru"=>"Перевод вызова"),
                "Hangup Customer"=>array("ru"=>"Завершить вызов"),
                "Web form"=>array("ru"=>"Веб форма"),
                "Web Form 2"=>array("ru"=>"Веб форма 2"),
                "Reset"=>array("ru"=>"Сброс"),
                "DISPOSITION CALL"=>array("ru"=>"Завершения вызова"),
                "Hangup Again"=>array("ru"=>"Повторное завершение вызова"),
                "PAUSE AGENT DIALING"=>array("ru"=>"Остановить работу агента"),
                "CLEAR FORM"=>array("ru"=>"Очистить форму"),
                "WEB FORM SUBMIT"=>array("ru"=>"веб-страницы отправки формы"),
                "Call Wrapup"=>array("ru"=>"Передышка"),
                "seconds remaining in wrapup"=>array("ru"=>"секунд до окончание передышки"),
                "Finish Wrapup and Move On"=>array("ru"=>"Окончить передышку и продолжить"),
                "Customer Time"=>array("ru"=>"Время клиентов"),
                "Customer Information"=>array("ru"=>"Сведения о клиенте"),
                "Channel"=>array("ru"=>"Линия"),
                "Lead Search"=>array("ru"=>"Поиск клиента"),
                "CLOSER INBOUND GROUP SELECTION"=>array("ru"=>"ВЫБОР ВХОДЯЩЕЙ ГРУППЫ"),
                "BLENDED CALLING(outbound activated)"=>array("ru"=>"Смешанный дозвон(исходящие активированы)"),
                "U - Undefined"=>array("ru"=>"Н - Не определено"),
                "F - Female"=>array("ru"=>"Ж - Женский"),
                "M - Male"=>array("ru"=>"М - Мужской"),
                "Show conference call channel information"=>array("ru"=>"Показать сведения о линии конференции"),
                "Alert is ON"=>array("ru"=>"Уведомления Выкл."),
                "Alert is OFF"=>array("ru"=>"Уведомления Вкл."),
                "Your Status"=>array("ru"=>"Ваше состояние"),
                "Calls Dialing"=>array("ru"=>"Вызовы"),
                "SELECT A PAUSE CODE"=>array("ru"=>"Выбор кода паузы"),
                "Pause Code Selection"=>array("ru"=>"Код Паузы"),
                "SELECT A PRESET"=>array("ru"=>"Выбор из телеф. книги"),
                "Presets Selection"=>array("ru"=>"Телеф. Книга"),
                "SELECT A GROUP ALIAS"=>array("ru"=>"Выбор превдонима группы"),
                "Group Alias Selection"=>array("ru"=>"Выбор превдонима группы"),
                "SELECT A DIAL IN-GROUP"=>array("ru"=>"Выбор звонка в группу"),
                "Dial In-Group Selection"=>array("ru"=>"Звонок в группу"),
                "Another live agent session was open using your user ID. It has been disabled. Click OK to continue to the agent screen"=>array("ru"=>"Другой агент сейчас работает с вашим уник. номером. Он будет отключен. Нажмите \"ОК\" для того чтобы продолжить"),
                "Your session has been disabled"=>array("ru"=>"Ваша сессия отключена"),
                "There is a time synchronization problem with your system, please tell your system administrator"=>array("ru"=>"В вашей системе есть ошибки синхронизации времени, сообщите пожалуйста своему системному администратору"),
                "SKIP LEAD"=>array("ru"=>"Пропустить"),
                "DIAL LEAD"=>array("ru"=>"Вызвать"),
                "or"=>array("ru"=>"или"),
                "Waiting for Ring"=>array("ru"=>"Ожидания ответа"),
                "Preview Call"=>array("ru"=>"Предпросмотр сведений о вызове"),
                "Dial Now"=>array("ru"=>"Вызвать"),
                "If you want to dial a number and have it NOT be added as a new lead, enter in the exact dialstring that you want to call in the Dial Override field below. To hangup this call you will have to open the CALLS IN THIS SESSION link at the bottom of the screen and hang it up by clicking on its channel link there"=>array("ru"=>"Вы хотите набрать номер, но не добавлять его в буфер, введите полный номер, который хотите вызвать, в поле ВВОД ДРУГОГО НОМЕРА ниже. Чтобы завершить этот вызов, Вам придется открыть ссылку ВЫЗОВЫ В ЭТОЙ СЕССИИ снизу на экране и завершить его кликом по ссылке на соответствующую линию"),
                "Dial Lead ID"=>array("ru"=>"Dial Lead ID"),
                "This option if checked will attempt to find the phone number in the system before inserting it as a new lead"=>array("ru"=>"При включении этой функции перед добавлением номера в качестве нового, его наличие в системе перепроверяется"),
                "Search Existing Leads"=>array("ru"=>"Искать в имеющихся номерах"),
                "digits only"=>array("ru"=>"только цифры"),
                "Phone Number"=>array("ru"=>"Номер телефона"),
                "This is usually a 1 in the USA-Canada"=>array("ru"=>"В США и Канаде это обычно единица"),
                "Dial Code"=>array("ru"=>"Код набора"),
                "all new manual dial leads will go into list"=>array("ru"=>"all new manual dial leads will go into list"),
                "will be added to the beginning of this number"=>array("ru"=>"будет добавлено в начало этого номера"),
                "a dial prefix of"=>array("ru"=>"префикс набора"),
                "Enter information below for the new lead you wish to call"=>array("ru"=>"Введите сведения о номере, который Вы хотите вызвать"),
                "in campaign"=>array("ru"=>"в кампании"),
                "NEW MANUAL DIAL LEAD FOR"=>array("ru"=>" НОВЫЙ РУЧНОЙ НАБОР НОМЕРА ДЛЯ"),
                "will be added to the beginning of this number"=>array("ru"=>""),
                "Dial Override"=>array("ru"=>"Ввод другого номера"),
                "Click Here to Choose a Group Alias"=>array("ru"=>"Кликните для выбора псевдонима группы"),
                "Note"=>array("ru"=>"Примечание"),
                "YOU MUST ENTER A PHONE NUMBER AND DIAL CODE TO USE FAST DIAL"=>array("ru"=>"ЧТОБЫ ПРОИЗВЕСТИ РУЧНОЙ НАБОР В РЕЖИМЕ АВТОДОЗВОНА ВАМ НУЖНО БЫТЬ В СОСТОЯНИИ ПАУЗЫ"),
                "Click Here to Deactivate"=>array("ru"=>"Нажмите здесь, чтобы выключить"),
                "Click Here to Activate"=>array("ru"=>"Нажмите здесь, чтобы включить"),
                "No-Call Dial"=>array("ru"=>"No-Call Dial"),
                "Code"=>array("ru"=>"Код"),
                "System Delay, Please try again"=>array("ru"=>"Система задержки, пожалуйста, попробуйте еще раз"),
		"Jan"=>array("ru"=>"ЯНВ"),
		"Feb"=>array("ru"=>"ФЕВ"),
		"Mar"=>array("ru"=>"МАР"),
		"Apr"=>array("ru"=>"АПР"),
		"May"=>array("ru"=>"МАЙ"),
		"Jun"=>array("ru"=>"ИЮН"),
		"Jul"=>array("ru"=>"ИЮЛ"),
		"Aug"=>array("ru"=>"АВГ"),
		"Sep"=>array("ru"=>"СЕН"),
		"Oct"=>array("ru"=>"ОКТ"),
		"Nov"=>array("ru"=>"НОЯ"),
		"Dec"=>array("ru"=>"ДЕК"),
                "When active, simply press the keyboard key for the desired disposition for this call. The call will then be hungup and dispositioned automatically"=>array("ru"=>"Если включено, просто нажмите клавишу выбора кода завершения. Вызов будет завершен автоматически"),
                "Disposition Hot Keys"=>array("ru"=>"Клавиши кодов завершения"),
                "Lead Dispositioned As"=>array("ru"=>"Вызов завершен с кодом"),
                "Your system does not have the email setting enabled"=>array("ru"=>"В настройках системы нет электронной почты"),
                "Invalid Username/Password"=>array("ru"=>"Неправильный логин/пароль"),
                "Invalid File Name"=>array("ru"=>"Некорректное имя файла"),
                "mail sent to"=>array("ru"=>"Почта отправоена к"),
                "mail could not be sent"=>array("ru"=>"Почта не может быть отправлена"),
                "Date received"=>array("ru"=>"Дата получения"),
                "From"=>array("ru"=>"От"),
                "Subject"=>array("ru"=>"Тема"),
                "Message"=>array("ru"=>"Сообщение"),
                "Attachments"=>array("ru"=>"Вложения"),
                "Response subject"=>array("ru"=>"Тема ответа"),
                "Response text"=>array("ru"=>"Текст ответа"),
                "Reply"=>array("ru"=>"Ответить"),
                "AGENT email frame"=>array("ru"=>"Окно почтовых сообщений клиента"),
                "ID variable missing"=>array("ru"=>"Нет новых сообщений"),
                "Refresh"=>array("ru"=>"Обновить"),
                "view notes"=>array("ru"=>"История примечаний"),
                "Hide Calls In Queue"=>array("ru"=>"Спрятать вызовы в очереди"),
                "Show Calls In Queue"=>array("ru"=>"Показать вызовы в очереди"),
                "Calls In Queue"=>array("ru"=>"Вызовы в очереди"),
                "Other Agents Status"=>array("ru"=>"Состояние других агентов"),
                "Available Agents Transfer"=>array("ru"=>"Перевод доступным агентам"),
                "View Comment Histor"=>array("ru"=>"Доска комментариев истории"),
                "Previous Callback Information"=>array("ru"=>"Сведения о предыдущем обратном вызове"),
                "Extended Alt Phone Information"=>array("ru"=>"Расширенные сведения о дополнительном номере"),
                "Alt Phone Info"=>array("ru"=>"Сведения о дополнительном номере"),
                "No one is in your session"=>array("ru"=>"Никого нет в вашей сессии"),
                "Call Agent Again"=>array("ru"=>"Повторный вызов агента"),
                "Customer has hung up"=>array("ru"=>"Клиент повесил трубку"),
                "Finish and Disposition Call"=>array("ru"=>"Завершить звонок с кодом"),
                "Any changes made to the customer information below at this time will not be comitted, You must change customer information before you Hangup the call"=>array("ru"=>"Любые изменения в сведениях о клиенте, произведенные в настоящий момент не будут сохранены. Это нужно делать до завершения вызова"),
                "Select a CallBack Date"=>array("ru"=>"Выбрать дату обратного звонка"),
                "Select a Date Below"=>array("ru"=>"Выберите дату ниже"),
                "Hours"=>array("ru"=>"Часы"),
                "Minutes"=>array("ru"=>"Минуты"),
                "MY CALLBACK ONLY"=>array("ru"=>"Обратный вызов только для меня"),
                "CB Comments"=>array("ru"=>"Комментарий к обратному вызову"),
                "CALLBACKS FOR AGENT"=>array("ru"=>"ОБРАТНЫЕ ВЫЗОВЫ АГЕНТА"),
                "To see information on one of the callbacks below, click on the INFO link. To call the customer back now, click on the DIAL link. If you click on a record below to dial it, it will be removed from the list."=>array("ru"=>"Чтобы посмотреть информацию об одном из обратного вызова ниже, нажмите на ссылку INFO. Чтобы позвонить клиенту обратно сейчас, нажмите на ссылку ВЫЗОВ. Если вы нажмете на запись ниже, чтобы набрать его, то он будет удален из списка."),
                "TERRITORY SELECTION"=>array("ru"=>"ВЫБОР ТЕРРИТОРИИ"),
                "BLENDED CALLING"=>array("ru"=>"Смешанный дозвон"),
                "AGENT CALL LOG"=>array("ru"=>" Журнал вызовов агента"),
                "SEARCH FOR A CONTACT"=>array("ru"=>"Поиск контакта"),
                "when doing a search for a contact, wildcard or partial search terms are not allowed"=>array("ru"=>"при выполнении поиска контакта, шаблона или частичное условия поиска не допускается"),
                "Contact search requests are all logged in the system"=>array("ru"=>"Просьбы связаться с поиска всех зарегистрированных в системе"),
                "Office Number"=>array("ru"=>"Номер офиса"),
                "First Name"=>array("ru"=>"Имя"),
                "Last Name"=>array("ru"=>"Фамилия"),
                "BU Name"=>array("ru"=>"Наименование фирмы"),
                "Department"=>array("ru"=>"Отдел"),
                "Group Name"=>array("ru"=>"Название группы"),
                "Job Title"=>array("ru"=>"Должность"),
                "Location"=>array("ru"=>"Расположение"),
                "Submit Search"=>array("ru"=>"Начать поиск"),
                "Reset Form"=>array("ru"=>"Восстановить форму"),
                "Search Results"=>array("ru"=>"Результаты поиска"),
                "CONTACTS SEARCH RESULTS"=>array("ru"=>"Результаты поиска контакто"),
                "SEARCH FOR A LEAD"=>array("ru"=>"Поиск клиента"),
                "when doing a search for a lead, the phone number, lead ID or"=>array("ru"=>"при выполнении поиска для свинца, номер телефона, или привести ID"),
                "are the best fields to use"=>array("ru"=>"Ведущие поисковые запросы все вошли в систему"),
                "Using the other fields may be slower.Lead searching does not allow for wildcard or partial search terms."=>array("ru"=>"Использование других областях может быть медленным. Ведущий поиски не позволяет шаблону или частичное условия поиска."),
                "Lead search requests are all logged in the system."=>array("ru"=>"Lead search requests are all logged in the system."),
                "Phone Number Fields"=>array("ru"=>"В полях Номер телефона"),
                "Main Phone Number"=>array("ru"=>"Основной номер телефона"),
                "Alternate Phone Number"=>array("ru"=>"Альтернативный номер телефона"),
                "Address3 Phone Number"=>array("ru"=>"Адрес номера телефона"),
                "Lead ID"=>array("ru"=>"Ун. Номер. Клиента"),
                "Call Notes LOG"=>array("ru"=>"История заметок по звонкам"),
                "Call Notes List"=>array("ru"=>"Список заметок по звонкам"),
                "Close Info Box"=>array("ru"=>"Закрыть информацыонное окно"),
                "-- SELECT A GROUP TO SEND YOUR CALL TO --"=>array("ru"=>"-- Выбор группы для отправки вашего звонка --"),
                "Local Closer"=>array("ru"=>"Местное завершение"),
                "CONSULTATIVE"=>array("ru"=>"Совещательный"),
                "Hangup Both Lines"=>array("ru"=>"Отключить обе линии"),
                "Number to CaLL"=>array("ru"=>"Номер для вызова"),
                "AGENTS"=>array("ru"=>"АГЕНТЫ"),
                "DIAL OVERRIDE"=>array("ru"=>"НАБОР ДРУГОГО НОМЕРА"),
                "LEAVE 3-WAY CALL"=>array("ru"=>"Покинуть трехсторонний вызов"),
                "Dial Blind Transfer"=>array("ru"=>"Слепой трансфер"),
                "Park Customer Dial"=>array("ru"=>"Сопровождаемый трансфер"),
                "Dial With Customer"=>array("ru"=>"Конференция"),
                "PRESETS"=>array("ru"=>"Телеф. книга"),
                "Contacts"=>array("ru"=>"Контакты"),
                "VoiveMail"=>array("ru"=>"Голосовая почта"),
                "Hangup Call"=>array("ru"=>"Завершить вызов"),
                "Hangup Xfer Line"=>array("ru"=>"Отключить линию перевода"),
                "Lead Info"=>array("ru"=>"Сведения о клиенте"),
                "Transfer - Conference"=>array("ru"=>"Функции перевода звонка"),
                "January"=>array("ru"=>"Январь"),
                "February"=>array("ru"=>"Февраль"),
                "March"=>array("ru"=>"Март"),
                "April"=>array("ru"=>"Апрель"),
                "May"=>array("ru"=>"Май"),
                "June"=>array("ru"=>"Июнь"),
                "July"=>array("ru"=>"Июль"),
                "August"=>array("ru"=>"Август"),
                "September"=>array("ru"=>"Сентабрь"),
                "October"=>array("ru"=>"Октябрь"),
                "November"=>array("ru"=>"Ноябрь"),
                "December"=>array("ru"=>"Декабрь"),
                "Su"=>array("ru"=>"Вс"),
                "Mo"=>array("ru"=>"Пн"),
                "Tu"=>array("ru"=>"Вт"),
                "We"=>array("ru"=>"Ср"),
                "Th"=>array("ru"=>"Чт"),
                "Fr"=>array("ru"=>"Пт"),
                "Sa"=>array("ru"=>"Сб"),
                "Quick Transfer"=>array("ru"=>"Быстрый перевод звонка"),
                "Custom Transfer"=>array("ru"=>"Ручной перевод звонка"),
                "maximize"=>array("ru"=>"Увеличить"),
                "minimize"=>array("ru"=>"Уменьшить"),
                "Last Call"=>array("ru"=>"Последний вызов"),
                "Manual Queue"=>array("ru"=>"Manual Queue"),
                "Placing call to"=>array("ru"=>"Placing call to"),
                "LIVE CALLS IN YOUR SESSION"=>array("ru"=>"Активные звонки в вашей сессии"),
                "REMOTE CHANNEL"=>array("ru"=>"Линия"),
                "VOLUME"=>array("ru"=>"Громкость"),
                "HANGUP"=>array("ru"=>"Отключить"),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),
                ""=>array("ru"=>""),

                "start recording"=>array("ru"=>"начать запись")
                );
        }
}


?>
